trigger:
- main

variables:
  imageName: callcenter-app
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: 'Build and Push to ACR'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker image'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'

    - task: Docker@2
      displayName: 'Build and push image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)' #Deve combaciare col nome della service connection
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Azure Container App'
  dependsOn: Build
  jobs:
  - job: DeployContainerApp
    displayName: 'Deploy to ACA'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name <APP_NAME> \
            --resource-group <RESOURCE_GROUP> \
            --image <ACR_NAME>.azurecr.io/$(imageName):$(tag)